/*
 * HelloWorldLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.www;

import java.util.EnumMap;
import java.util.HashMap;
import java.util.Map;

import com.example.www.models.*;

public class Configuration {
    /**
     * Current API environment
     */
    public static Environments environment = Environments.PRODUCTION;

    /**
     *  defaultHost value
     */
    public static String defaultHost = "www.example.com";

    /**
     * Get base URI by current environment
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public static String getBaseUri(Servers server) {
        StringBuilder baseUrl = new StringBuilder(environmentsMap.get(Configuration.environment).get(server));
        Map<String, Object> parameters = new HashMap<String, Object>() {
            private static final long serialVersionUID = -1743185654L;
            {
                put("defaultHost", Configuration.defaultHost);
            }
        };
        APIHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }
    
    /**
     * Get base URI by current environment
     * @return Processed base URI
     */
    public static String getBaseUri() {
        return Configuration.getBaseUri(Servers.ENUM_DEFAULT);
    }
    
    /**
     * Map of all base URLs by environments and server aliases 
     */
    private static EnumMap<Environments, EnumMap<Servers, String>> environmentsMap = new EnumMap<Environments, EnumMap<Servers,String>>(Environments.class) {
        private static final long serialVersionUID = -633999557L;
        {
            put(Environments.PRODUCTION, new EnumMap<Servers, String>(Servers.class) {
                private static final long serialVersionUID = 775121450708L;
                {
                    put(Servers.ENUM_DEFAULT, "http://{defaultHost}");
                }
            });
        }
    };
}
